"""Handwritten correctness cases assigned to registered operations.

This table is test evidence, not a second support policy. Production registries
define accepted calls and tile ops; these entries only point at tests that
exercise their observable numerical or state semantics.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RuntimeCase:
    target_ids: tuple[str, ...]
    tests: tuple[str, ...]


RUNTIME_CASES = (
    RuntimeCase(
        target_ids=("call:tirx.cuda.func_call",),
        tests=(
            (
                "integration/test_opaque_helper_artifact.py::"
                "test_opaque_or_spoofed_cuda_helpers_are_rejected"
            ),
            (
                "integration/test_opaque_helper_artifact.py::"
                "test_smem_descriptor_offset_wraps_only_the_low_32_bits"
            ),
            (
                "integration/test_opaque_helper_artifact.py::"
                "test_smem_descriptor_make_lo_uniform_broadcasts_only_lane_zero_low_bits"
            ),
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.cp_async_bulk_tensor_g2s_cta_im2col",
            "call:tirx.ptx.cp_async_bulk_tensor_s2g_im2col_no_offs_w",
        ),
        tests=(
            "runtime/test_tma_u6.py::test_tma_u6_layout_and_checkers",
            "runtime/test_tma_atomicity.py::test_tma_atomicity_layout_and_checkers",
            "runtime/test_tma_atomicity.py::test_tma_atomicity_direction_restrictions",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.st_async_release", "call:tirx.ptx.red_async_release"),
        tests=(
            "runtime/test_async_release.py::test_async_release_payloads",
            "runtime/test_async_release.py::test_async_release_publishes_only_pre_issue_work",
            "runtime/test_async_release.py::test_bulk_wait_does_not_acquire_async_release",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.cp_async_bulk_tensor_g2s_cta_override_address_im2col",
            "call:tirx.ptx.cp_async_bulk_tensor_g2s_cluster_im2col",
            "call:tirx.ptx.cp_async_bulk_tensor_g2s_cluster_override_address_im2col",
            "call:tirx.ptx.cp_async_bulk_tensor_s2g_override_address_im2col_no_offs_w",
            "call:tirx.ptx.cp_reduce_async_bulk_tensor_im2col_no_offs_w",
            "call:tirx.ptx.cp_reduce_async_bulk_tensor_override_address_im2col_no_offs_w",
        ),
        tests=(
            "runtime/test_tma_im2col.py::test_im2col_spatial",
            "runtime/test_tma_im2col.py::test_im2col_store_and_reduce",
            "runtime/test_tma_im2col.py::test_im2col_interleaved",
            "runtime/test_tma_im2col_multiissuer.py::test_im2col_per_thread_coordinates_and_offsets",
            "runtime/test_tma_im2col_multiissuer.py::test_wide_im2col_per_thread_halo_offset_and_completion",
            "runtime/test_tma_im2col_multiissuer.py::test_im2col_multiissuer_requires_completion_wait",
            "runtime/test_copy_multicast32.py::test_multicast_high_bit_targets_and_bounds[im2col]",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.ld_proxy_readonly",),
        tests=("runtime/test_readonly_proxy.py::test_readonly_proxy_values_and_disjoint_writes",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tensormap_cp_fenceproxy",
            "call:tirx.ptx.tensormap_replace_interleave_layout",
        ),
        tests=(
            "runtime/test_tensormap_predicates.py::test_tensor_map_predicate_effects",
            "runtime/test_tensormap_predicates.py::test_tensor_map_predicates_retain_errors",
            "microtests/test_remaining_memory_ops.py::test_tensor_map_predicates_gpu_oracle",
        ),
    ),
    RuntimeCase(
        target_ids=tuple(
            f"call:tirx.ptx.tcgen05_mma_{prefix}ti16_{mode}{mask}"
            for prefix, masks in (("sp_", ("",)), ("ws_sp_", ("", "_mask")))
            for mode in ("ss", "ts")
            for mask in masks
        ),
        tests=("runtime/test_tcgen05_ti16.py::test_sparse_ti16_metadata",),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.tensormap_replace_swizzle_mode_sm103a",),
        tests=("runtime/test_tma_swizzle96.py::test_swizzle96_documented_layout",),
    ),
    RuntimeCase(
        target_ids=tuple(
            f"call:tirx.ptx.mbarrier_{action}{parity}_report{value}{hint}"
            for action, hints in (("test_wait", ("",)), ("try_wait", ("", "_hint")))
            for parity in ("", "_parity")
            for value in ("", "_value")
            for hint in hints
        ),
        tests=("runtime/test_mbarrier_report.py::test_report_queries_and_phase_reset",),
    ),
    RuntimeCase(
        target_ids=tuple(
            f"call:tirx.ptx.cp_async_bulk{tensor}_g2s_{space}_report"
            for tensor in ("", "_tensor")
            for space in ("cta", "cluster")
        ),
        tests=(
            "runtime/test_mbarrier_report.py::test_report_queries_and_phase_reset",
            "runtime/test_mbarrier_report.py::test_tensor_copy_report",
            "runtime/test_mbarrier_report.py::test_gather4_report_samples_only_selected_source_rows",
            "runtime/test_mbarrier_report.py::test_multicast_report_targets",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.tcgen05_mma_ti16_ss", "call:tirx.ptx.tcgen05_mma_ti16_ts"),
        tests=("runtime/test_tcgen05_ti16.py::test_ti16_exact_accumulation",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_mma_lut_b_ss",
            "call:tirx.ptx.tcgen05_mma_lut_b_ts",
        ),
        tests=("runtime/test_tcgen_lut_b.py::test_dense_lut_b_segments_and_cta_partition",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_mma_block_scale_lut_b_ss",
            "call:tirx.ptx.tcgen05_mma_block_scale_lut_b_ts",
        ),
        tests=("runtime/test_tcgen_lut_b.py::test_block_lut_b_scales_and_packed_tmem",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_mma_ashift_collector_b_ts",
            "call:tirx.ptx.tcgen05_mma_sp_ashift_collector_b_ts",
        ),
        tests=("runtime/test_tcgen_ashift.py::test_ashift_followed_by_mma",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_mma_block_scale_collector_ab_ss",
            "call:tirx.ptx.tcgen05_mma_block_scale_collector_ab_ts",
        ),
        tests=("runtime/test_tcgen05_block_tmem.py::test_block_scale_implicit_size_with_discard",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_mma_sp_block_scale_collector_ab_ss",
            "call:tirx.ptx.tcgen05_mma_sp_block_scale_collector_ab_ts",
        ),
        tests=(
            "runtime/test_tcgen05_sparse_block.py::test_sparse_block_scales_and_metadata",
            "runtime/test_tcgen05_sparse_k128.py::test_sparse_k128_packing_scales_and_transpose",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_mma_ti16_ss_collector_b",
            "call:tirx.ptx.tcgen05_mma_ti16_ts_collector_b",
            "call:tirx.ptx.tcgen05_mma_collector_ab_ss",
            "call:tirx.ptx.tcgen05_mma_collector_ab_ts",
        ),
        tests=("runtime/test_tcgen05_ti16.py::test_ti16_exact_accumulation",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_mma_sp_ti16_ss_collector_b",
            "call:tirx.ptx.tcgen05_mma_sp_ti16_ts_collector_b",
        ),
        tests=("runtime/test_tcgen05_ti16.py::test_sparse_ti16_metadata",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_mma_sp_collector_ab_ss",
            "call:tirx.ptx.tcgen05_mma_sp_collector_ab_ts",
        ),
        tests=(
            "runtime/test_tcgen05_ti16.py::test_sparse_ti16_metadata",
            "runtime/test_tcgen05_tf32.py::test_tf32_sparse_metadata",
            "runtime/test_tcgen05_sparse_b16.py::test_sparse_b16_layouts_and_codecs",
            "runtime/test_tcgen05_sparse_narrow.py::test_sparse_narrow_layouts_and_codecs",
            "runtime/test_tcgen05_sparse_narrow.py::test_sparse_narrow_k128",
        ),
    ),
    RuntimeCase(
        target_ids=tuple(
            f"call:tirx.ptx.tcgen05_mma_ws_ti16_{mode}{mask}"
            for mode in ("ss", "ts")
            for mask in ("", "_mask")
        ),
        tests=("runtime/test_tcgen05_ti16.py::test_ti16_ws_banks_and_column_mask",),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.red_async",),
        tests=("runtime/test_red_async.py::test_red_async",),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.mbarrier_inval", "call:tirx.ptx.mbarrier_check_layout"),
        tests=(
            "runtime/test_mbarrier_maintenance.py::test_maintenance_predicates_and_carriers",
            "runtime/test_mbarrier_maintenance.py::test_maintenance_active_addresses_still_checked",
        ),
    ),
    RuntimeCase(
        target_ids=tuple(
            f"call:tirx.ptx.{stem}{override}_im2col{evict}"
            for stem, evict in (
                ("cp_async_bulk_tensor_prefetch", ""),
                ("cp_async_bulk_tensor_prefetch", "_evict_last"),
                ("applypriority_async_bulk_tensor", ""),
            )
            for override in ("", "_override_address")
        ),
        tests=("runtime/test_im2col_cache_hints.py::test_im2col_cache_hints",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.spcompress",
        ),
        tests=(
            "runtime/test_sm107_register_predicates.py::test_sm107_register_predicates",
            "microtests/test_sm107_register_predicates.py::test_sm107_register_predicates_gpu",
        ),
    ),
    RuntimeCase(
        target_ids=tuple(
            f"call:tirx.ptx.createpolicy_{suffix}"
            for suffix in ("range", "fraction", "fractional", "cvt")
        ),
        tests=("runtime/test_cache_policy.py::test_cache_policy",),
    ),
    RuntimeCase(
        target_ids=tuple(
            f"call:tirx.ptx.{name}_red_{kind}{suffix}"
            for name in ("bar", "barrier")
            for kind in ("popc", "pred")
            for suffix in ("", "_count")
        ),
        tests=("runtime/test_bar_reduce.py::test_bar_reduce",),
    ),
    RuntimeCase(
        target_ids=tuple(
            "call:tirx.ptx.mbarrier_" + action + "_multicast32" + suffix
            for action, suffix in (
                ("arrive", ""),
                ("arrive", "_nocount"),
                ("arrive_drop", ""),
                ("arrive_drop", "_nocount"),
                ("arrive_expect_tx", ""),
                ("arrive_drop_expect_tx", ""),
                ("expect_tx", ""),
                ("complete_tx", ""),
            )
        ),
        tests=("runtime/test_mbarrier_multicast.py::test_mbarrier_multicast32",),
    ),
    RuntimeCase(
        target_ids=tuple(
            "call:tirx.ptx.mbarrier_arrive_drop" + suffix
            for suffix in (
                "",
                "_nocount",
                "_state",
                "_count_state",
                "_expect_tx",
                "_expect_tx_state",
                "_no_complete",
                "_no_complete_sink",
            )
        ),
        tests=("runtime/test_mbarrier_drop.py::test_mbarrier_drop",),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.ldmatrix_s8_s4",),
        tests=("runtime/test_ldmatrix_b8.py::test_ldmatrix_s8_s4",),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.ldu", "call:tirx.ptx.ldu_vec"),
        tests=(
            "runtime/test_memory_coverage_next.py::test_next_memory_contracts[ldu]",
            "microtests/test_memory_coverage_next.py::test_next_memory_contracts_match_gpu[ldu]",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.mbarrier_arrive_no_complete",
            "call:tirx.ptx.mbarrier_arrive_no_complete_sink",
        ),
        tests=(
            "runtime/test_memory_coverage_next.py::test_next_memory_contracts[no_complete]",
            "microtests/test_memory_coverage_next.py::test_next_memory_contracts_match_gpu[no_complete]",
        ),
    ),
    RuntimeCase(
        target_ids=tuple(
            f"call:tirx.ptx.tensormap_replace_{field}"
            for field in ("rank", "elemtype", "fill_mode", "swizzle_mode")
        ),
        tests=(
            "runtime/test_memory_coverage_next.py::test_next_memory_contracts[descriptor_f32]",
            "runtime/test_memory_coverage_next.py::test_next_memory_contracts[descriptor_tf32]",
            "microtests/test_memory_coverage_next.py::test_next_memory_contracts_match_gpu[descriptor_f32]",
            "microtests/test_memory_coverage_next.py::test_next_memory_contracts_match_gpu[descriptor_tf32]",
        ),
    ),
    RuntimeCase(
        target_ids=tuple(
            f"call:tirx.ptx.{name}"
            for name in (
                "atom_exch",
                "atom_bitbucket",
                "atom_cas_bitbucket",
                "atom_exch_bitbucket",
                "atom_vec_f32_bitbucket",
                "atom_half",
                "atom_half_bitbucket",
                "atom_vec_half",
                "atom_vec_half_bitbucket",
                "red_vec_half",
                "red_vec_f32",
                "mbarrier_arrive_state",
                "mbarrier_arrive_expect_tx_state",
                "mbarrier_test_wait",
                "mbarrier_try_wait_hint",
                "mapa_u64_raw",
                "mapa_u64_shared",
                "getctarank",
                "getctarank_generic",
                "isspacep",
                "cvta_generic",
                "cp_async_wait_all",
                "st_async",
            )
        ),
        tests=(
            "runtime/test_memory_sync_coverage.py::test_memory_sync_extensions",
            "microtests/test_memory_sync_coverage.py::test_memory_sync_extensions_match_gpu",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.isnullptr",),
        tests=("runtime/test_pointer_null.py::test_isnullptr_on_backed_pointers",),
    ),
    RuntimeCase(
        target_ids=("call:tirx.reinterpret",),
        tests=(
            "integration/test_artifact_build.py::test_typed_raw_scalar_calls_execute_with_warp_semantics",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.cuda.ldg",),
        tests=(
            "runtime/test_cuda_generic_scalar_forms.py::test_cuda_ldg_supports_cuda_scalar_overloads",
            "runtime/test_cuda_ldg_overloads.py::test_cuda_ldg_packed_vectors_preserve_physical_bits",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.add",
            "call:tirx.ptx.fma",
            "call:tirx.ptx.mul",
            "call:tirx.ptx.mul_half",
            "call:tirx.ptx.sub",
            "call:tirx.ptx.fma_half",
            "call:tirx.ptx.mad_int",
            "call:tirx.ptx.mul_int",
            "call:tirx.ptx.sub_int",
        ),
        tests=(
            "runtime/test_scalar_control.py::test_ptx_dps_sub_and_f64_arithmetic",
            "runtime/test_packed_f16x2_arithmetic.py::test_packed_f16x2_multiplies_both_halves_with_one_rounding_step",
            "runtime/test_ptx_new_register_semantics.py::test_ptx_new_register_semantics_match_independent_oracles",
            "runtime/test_ptx_new_register_semantics.py::test_ptx_scalar_moves_and_mad_lo_s64_match_bit_and_wrap_oracles",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.copysign",
            "call:tirx.ptx.cos",
            "call:tirx.ptx.mad_f",
            "call:tirx.ptx.neg_half",
            "call:tirx.ptx.sin",
            "call:tirx.ptx.sqrt",
        ),
        tests=(
            "runtime/test_ptx_float_register_ops.py::test_copysign_copies_only_the_sign_bit",
            "runtime/test_ptx_float_register_ops.py::test_neg_half_models_finite_values_and_chooses_the_documented_nan_representative",
            "runtime/test_ptx_float_register_ops.py::test_mad_f_reuses_exact_fused_arithmetic_for_every_supported_modifier",
            "runtime/test_ptx_float_register_ops.py::test_sqrt_all_rounding_modes_and_ftz_forms_match_an_exact_square_oracle",
            "runtime/test_ptx_float_register_ops.py::test_trigonometric_approximations_obey_special_values_ftz_and_error_bound[sin]",
            "runtime/test_ptx_float_register_ops.py::test_trigonometric_approximations_obey_special_values_ftz_and_error_bound[cos]",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.abs_half",
            "call:tirx.ptx.abs_f",
            "call:tirx.ptx.add_int",
            "call:tirx.ptx.mov_pack_b32x2",
            "call:tirx.ptx.mov_pack_b64x2",
            "call:tirx.ptx.mov_unpack_b16x2",
            "call:tirx.ptx.mov_unpack_b32x2",
            "call:tirx.ptx.xor",
        ),
        tests=(
            "runtime/test_ptx_register_bits.py::test_ptx_register_bit_ops_match_ptx_value_and_bit_semantics",
            "runtime/test_mov_forms.py::test_mov_aliased_sources_destinations_and_predicate",
            "runtime/test_ptx_register_bits.py::test_ptx_half_abs_and_setp_match_bitwise_numpy_oracle",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.neg",
        ),
        tests=(
            "runtime/test_register_extensions.py::test_register_extensions",
            "runtime/test_register_extensions.py::test_register_extensions_gpu",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.clmad",),
        tests=("runtime/test_ptx_clmad.py::test_ptx_clmad_hi_and_lo_match_independent_gf2_oracle",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.lop3",
            "call:tirx.ptx.lop3_bool",
            "call:tirx.ptx.lop3_bool_sink",
        ),
        tests=(
            "runtime/test_ptx_lop3.py::test_ptx_lop3_all_destination_shapes_match_truth_table_oracle",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.div",
            "call:tirx.ptx.dp2a",
            "call:tirx.ptx.dp4a",
            "call:tirx.ptx.mad24",
            "call:tirx.ptx.mad_wide",
            "call:tirx.ptx.mul24",
            "call:tirx.ptx.mul_wide",
            "call:tirx.ptx.neg_int",
            "call:tirx.ptx.rem",
            "call:tirx.ptx.sad",
        ),
        tests=(
            "runtime/test_ptx_integer_arithmetic.py::test_ptx_div_all_legal_forms_match_independent_integer_oracle",
            "runtime/test_ptx_integer_arithmetic.py::test_ptx_dp2a_all_legal_forms_match_independent_packed_lane_oracle",
            "runtime/test_ptx_integer_arithmetic.py::test_ptx_dp4a_all_legal_forms_match_independent_packed_lane_oracle",
            "runtime/test_ptx_integer_arithmetic.py::test_ptx_mad24_all_legal_forms_match_independent_integer_oracle",
            "runtime/test_ptx_integer_arithmetic.py::test_ptx_mad_wide_all_legal_forms_match_independent_integer_oracle",
            "runtime/test_ptx_integer_arithmetic.py::test_ptx_mul24_all_legal_forms_match_independent_integer_oracle",
            "runtime/test_ptx_integer_arithmetic.py::test_ptx_mul_wide_all_legal_forms_match_independent_integer_oracle",
            "runtime/test_ptx_integer_arithmetic.py::test_ptx_neg_int_all_legal_forms_match_wrapping_negation_oracle",
            "runtime/test_ptx_integer_arithmetic.py::test_ptx_rem_all_legal_forms_match_independent_integer_oracle",
            "runtime/test_ptx_integer_arithmetic.py::test_ptx_sad_all_legal_forms_match_independent_integer_oracle",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.abs",
            "call:tirx.ptx.bfe",
            "call:tirx.ptx.bfi",
            "call:tirx.ptx.bfind",
            "call:tirx.ptx.bmsk",
            "call:tirx.ptx.brev",
            "call:tirx.ptx.clz",
            "call:tirx.ptx.cnot",
            "call:tirx.ptx.not",
            "call:tirx.ptx.popc",
            "call:tirx.ptx.shf",
            "call:tirx.ptx.szext",
            "call:tirx.ptx.fns",
        ),
        tests=(
            "runtime/test_ptx_bitops.py::test_ptx_bitop_forms_and_predicates_match_independent_oracle",
            "runtime/test_logic_carriers.py::test_logic_carriers_preserve_bits_and_masks",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.set_packed",),
        tests=(
            "runtime/test_ptx_set_packed.py::test_ptx_set_packed_all_legal_forms_match_independent_lane_oracle",
            "runtime/test_ptx_set_packed.py::test_ptx_set_packed_preserves_every_b32_carrier_cross_product",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.set",
            "call:tirx.ptx.set_bool",
            "call:tirx.ptx.set_half",
            "call:tirx.ptx.set_half_bool",
            "call:tirx.ptx.setp_bool",
            "call:tirx.ptx.setp_bool_pq",
            "call:tirx.ptx.setp_half_bool",
            "call:tirx.ptx.setp_half_bool_pq",
            "call:tirx.ptx.setp_half_pq",
            "call:tirx.ptx.setp_pq",
            "call:tirx.ptx.slct",
            "call:tirx.ptx.testp",
        ),
        tests=(
            "runtime/test_ptx_compare_semantics.py::test_compare_and_classify_match_independent_bit_oracle",
            "runtime/test_ptx_compare_semantics.py::test_slct_preserves_payload_bits_and_defines_nan_zero_and_ftz",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.spdecompress",),
        tests=(
            "runtime/test_ptx_spdecompress.py::test_ptx_spdecompress_matches_low_bit_first_sparse_scatter",
            "runtime/test_ptx_spdecompress.py::test_ptx_spdecompress_executes_the_128_register_output_boundary",
            "runtime/test_ptx_spdecompress.py::test_ptx_spdecompress_rejects_metadata_index_at_or_above_dst",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.add_mixed_vec_down_bf16",
            "call:tirx.ptx.add_mixed_vec_down_f16",
            "call:tirx.ptx.add_mixed_vec_up",
            "call:tirx.ptx.fma_mixed_vec",
            "call:tirx.ptx.mul_mixed_vec_bf16_f16",
            "call:tirx.ptx.mul_mixed_vec_down_bf16",
            "call:tirx.ptx.mul_mixed_vec_down_f16",
            "call:tirx.ptx.mul_mixed_vec_f16_bf16",
            "call:tirx.ptx.sub_mixed_vec_down_bf16",
            "call:tirx.ptx.sub_mixed_vec_down_f16",
            "call:tirx.ptx.sub_mixed_vec_up",
        ),
        tests=(
            "runtime/test_ptx_mixed_vector_arithmetic.py::test_all_36_mixed_vector_arithmetic_forms_execute_with_packed_lane_semantics",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.and",
            "call:tirx.ptx.or",
            "call:tirx.ptx.prmt",
            "call:tirx.ptx.selp",
            "call:tirx.ptx.setp",
            "call:tirx.ptx.setp_half",
        ),
        tests=(
            "runtime/test_ptx_register_bits.py::test_ptx_setp_and_predicate_selp_match_numpy_control_oracle",
            "runtime/test_logic_carriers.py::test_logic_carriers_preserve_bits_and_masks",
            "runtime/test_ptx_register_bits.py::test_ptx_half_abs_and_setp_match_bitwise_numpy_oracle",
            "runtime/test_ptx_new_register_semantics.py::test_ptx_new_register_semantics_match_independent_oracles",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.mov",
            "call:tirx.ptx.mov_pack_b16x2",
            "call:tirx.ptx.shl",
        ),
        tests=(
            "runtime/test_ptx_bitops.py::test_ptx_bitop_forms_and_predicates_match_independent_oracle",
            "runtime/test_mov_forms.py::test_mov_pointer_identity_masks_and_nulls",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.shr",),
        tests=(
            "runtime/test_ptx_bitops.py::test_ptx_bitop_forms_and_predicates_match_independent_oracle",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.cvt_pack",
            "call:tirx.ptx.cvt_pack_c",
            "call:tirx.ptx.mov_pack_b16x4",
            "call:tirx.ptx.mov_pack_b32x4",
            "call:tirx.ptx.mov_unpack_b16x4",
            "call:tirx.ptx.mov_unpack_b32x4",
            "call:tirx.ptx.mov_unpack_b64x2",
        ),
        tests=(
            "runtime/test_ptx_move_pack_extended.py::test_cvt_pack_matches_saturating_two_field_oracle",
            "runtime/test_ptx_move_pack_extended.py::test_cvt_pack_c_matches_all_six_subbyte_forms_and_b32_carrier_bits",
            "runtime/test_ptx_move_pack_extended.py::test_mov_pack_b16x4_places_first_integer_carrier_in_low_bits",
            "runtime/test_ptx_move_pack_extended.py::test_mov_pack_b32x4_preserves_float_carrier_payloads_and_lane_order",
            "runtime/test_ptx_move_pack_extended.py::test_mov_unpack_b16x4_preserves_lane_order_and_explicit_sinks",
            "runtime/test_ptx_move_pack_extended.py::test_mov_unpack_b32x4_preserves_b128_halves_as_float_carrier_bits",
            "runtime/test_ptx_move_pack_extended.py::test_mov_unpack_b64x2_preserves_low_then_high_halves_as_float_bits",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.activemask",
            "call:tirx.ptx.elect_sync",
            "call:tirx.ptx.match_all_sync",
            "call:tirx.ptx.match_all_sync_p",
            "call:tirx.ptx.match_any_sync",
            "call:tirx.ptx.movmatrix",
            "call:tirx.ptx.redux_sync",
            "call:tirx.ptx.redux_sync_bitwise",
            "call:tirx.ptx.redux_sync_f32",
            "call:tirx.ptx.shfl_sync",
            "call:tirx.ptx.shfl_sync_p",
            "call:tirx.ptx.vote_sync",
            "call:tirx.ptx.vote_sync_ballot",
        ),
        tests=(
            "runtime/test_ptx_warp_collectives.py::test_raw_ptx_warp_collectives_match_ptx_membermask_and_bit_semantics",
            "runtime/test_ptx_warp_collectives.py::test_raw_ptx_movmatrix_b16_matches_register_fragment_transpose",
            "runtime/test_ptx_warp_collectives.py::test_raw_ptx_f32_reductions_match_nan_and_signed_zero_semantics",
            "runtime/test_ptx_warp_collectives.py::test_raw_ptx_match_and_activemask_preserve_float_carrier_bits",
            "runtime/test_ptx_warp_collectives.py::test_raw_ptx_match_redux_and_activemask_match_warp_oracles",
            "runtime/test_ptx_warp_collectives.py::test_raw_ptx_vote_and_integer_reductions_match_member_lane_oracles",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.barrier_cluster_wait",),
        tests=(
            "integration/test_memory_artifact.py::test_cluster_barrier_accepts_default_release_and_unaligned_forms",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.cuda.mbarrier_wait",),
        tests=(
            "integration/test_artifact_build.py::test_physical_mbarrier_reuses_phase_and_completes_numeric_transactions_directly",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.tvm_storage_sync",),
        tests=(
            "runtime/test_sync_runtime_domain_oracle.py::test_tvm_storage_sync_roundtrip_preserves_shared_values",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.mbarrier_wait_acquire_cluster",
            "call:tirx.ptx.clusterlaunchcontrol_query_cancel_get_first_ctaid",
            "call:tirx.ptx.clusterlaunchcontrol_query_cancel_get_first_ctaid_v4",
            "call:tirx.ptx.clusterlaunchcontrol_query_cancel_is_canceled",
            "call:tirx.ptx.clusterlaunchcontrol_try_cancel",
        ),
        tests=(
            "runtime/test_sync_runtime_domain_oracle.py::test_clc_no_work_completion_and_cluster_acquire_wait",
            "runtime/test_sync_runtime_domain_oracle.py::test_clc_first_ctaid_y_and_z_are_zero_in_linear_launch_model",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.cp_async_bulk_tensor_g2s_cluster",
            "call:tirx.ptx.cp_async_bulk_tensor_g2s_cta",
            "call:tirx.ptx.cp_async_bulk_tensor_prefetch",
            "call:tirx.ptx.cp_async_bulk_tensor_s2g",
            "call:tirx.ptx.cp_reduce_async_bulk_tensor",
        ),
        tests=(
            "runtime/test_raw_tma_codegen.py::test_raw_tma_s2g_returns_the_tensor_map_output",
            "runtime/test_raw_tma_codegen.py::test_raw_tma_s2g_instruction_predicate_controls_the_store",
            "runtime/test_memory_ops.py::test_raw_tma_gather4_bar_address_and_prefetch",
            "runtime/test_memory_ops.py::test_raw_tma_reduce_uses_retained_logical_dtype",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.reinterpret",),
        tests=(
            "runtime/test_logic_carriers.py::test_half_reinterpret_preserves_storage_payloads",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.cp_async_bulk_prefetch",),
        tests=(
            "runtime/test_non_tensor_bulk_forms.py::test_raw_bulk_prefetch_preserves_global_memory",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.cp_async_bulk_tensor_g2s_cluster_multicast16",
            "call:tirx.ptx.cp_async_bulk_tensor_g2s_cluster_multicast32",
        ),
        tests=(
            "runtime/test_tma_multiissuer.py::test_tma_multiissuer_coordinates_and_target_completion",
            "runtime/test_tma_multiissuer.py::test_tma_multiissuer_requires_wait_and_disjoint_destinations",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.applypriority",
            "call:tirx.ptx.applypriority_async_bulk",
            "call:tirx.ptx.applypriority_async_bulk_tensor",
            "call:tirx.ptx.cp_async_bulk_prefetch_evict_last",
            "call:tirx.ptx.cp_async_bulk_tensor_prefetch_evict_last",
            "call:tirx.ptx.prefetch_valid_addr",
            "call:tirx.ptx.prefetchu",
        ),
        tests=(
            "runtime/test_cache_hint_ops.py::test_cache_hint_family_validates_operands_without_changing_memory",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.discard",),
        tests=(
            "runtime/test_discard.py::test_discard_range_and_predication",
            "runtime/test_discard.py::test_discard_indeterminate_read_and_alignment",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.cuda.mov_sreg",),
        tests=(
            "runtime/test_scalar_control.py::test_fetch_register_models_logical_coordinates_and_uses_stable_time_tokens",
            "runtime/test_scalar_control.py::test_fetch_register_separates_launched_warps_from_sm100_warp_identifier_capacity",
            "runtime/test_launch_resource_facts.py::test_smid_defaults_to_zero_in_execution_and_both_checkers",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.fdividef",
            "call:tirx.cuda.iket_mark",
            "call:tirx.cuda.iket_official_event",
            "call:tirx.cuda.iket_range_end",
            "call:tirx.cuda.iket_range_pop",
            "call:tirx.cuda.iket_range_push",
            "call:tirx.cuda.iket_range_start",
            "call:tirx.cuda.iket_sentinel_token",
            "call:tirx.ptx.cvt",
            "call:tirx.ptx.cvt_94_narrow_f32",
            "call:tirx.ptx.cvt_94_narrow_fp16x2",
            "call:tirx.ptx.cvt_bf16x2_f32",
            "call:tirx.ptx.cvt_bf16x2_f4x2",
            "call:tirx.ptx.cvt_bf16x2_f6x2",
            "call:tirx.ptx.cvt_bf16x2_f8x2",
            "call:tirx.ptx.cvt_bf16x2_s2f6x2",
            "call:tirx.ptx.cvt_bf16x2_ue8m0x2",
            "call:tirx.ptx.cvt_bf16x2_ue5m3x2",
            "call:tirx.ptx.cvt_f16x2_f32",
            "call:tirx.ptx.cvt_f16x2_f4x2",
            "call:tirx.ptx.cvt_f16x2_f6x2",
            "call:tirx.ptx.cvt_f16x2_f8x2",
            "call:tirx.ptx.cvt_f16x2_ue5m3x2",
            "call:tirx.ptx.cvt_f4x2_f32",
            "call:tirx.ptx.cvt_f4x2_fp16x2",
            "call:tirx.ptx.cvt_f6x2_f32",
            "call:tirx.ptx.cvt_f6x2_fp16x2",
            "call:tirx.ptx.cvt_f8x2_f32",
            "call:tirx.ptx.cvt_f8x2_fp16x2",
            "call:tirx.ptx.cvt_pzo_fp16x2_f32",
            "call:tirx.ptx.cvt_pzo_scalar_f32",
            "call:tirx.ptx.cvt_pzo_tf32_f32",
            "call:tirx.ptx.cvt_rs_bf16x2_f32",
            "call:tirx.ptx.cvt_rs_f16x2_f32",
            "call:tirx.ptx.cvt_rs_f4x4_f32",
            "call:tirx.ptx.cvt_rs_f6x4_f32",
            "call:tirx.ptx.cvt_rs_f8x4_f32",
            "call:tirx.ptx.cvt_s2f6x2_bf16x2",
            "call:tirx.ptx.cvt_s2f6x2_f32",
            "call:tirx.ptx.cvt_tf32_f32",
            "call:tirx.ptx.cvt_ue8m0x2_bf16x2",
            "call:tirx.ptx.cvt_ue8m0x2_f32",
            "call:tirx.ptx.cvt_ue5m3x2_f32",
            "call:tirx.ptx.cvt_ue5m3x2_f32_scaled",
            "call:tirx.ptx.cvt_ue5m3x2_fp16x2",
            "call:tirx.ptx.cvt_ue5m3x2_fp16x2_scaled",
        ),
        tests=(
            "runtime/test_scalar_control.py::test_current_scalar_device_intrinsics_have_stable_numeric_representatives",
            "microtests/test_ptx_cvt_fp8.py::test_packed_fp8_cvt_kernel_matches_gpu_goldens",
            "microtests/test_ptx_cvt_narrow.py::test_narrow_cvt_kernel_matches_gpu_goldens",
            "microtests/test_ptx_cvt_scalar.py::test_scalar_cvt_matches_recorded_gpu_goldens[scalar_cvt_float_to_int]",
            "microtests/test_ptx_cvt_scalar.py::test_scalar_cvt_matches_recorded_gpu_goldens[scalar_cvt_narrowing]",
            "microtests/test_ptx_cvt_scalar.py::test_scalar_cvt_matches_recorded_gpu_goldens[scalar_cvt_rounded_conversions]",
            "integration/test_packed_ptx_cvt_and_return.py::test_packed_ptx_cvt_matches_instruction_lane_and_rounding_contract",
            "runtime/test_ptx_cvt_pzo.py::test_pzo_is_post_conversion_and_applies_to_each_packed_result",
            "runtime/test_ptx_cvt_94.py::test_ptx94_non_pzo_cvt_families_match_independent_bit_oracle",
            "runtime/test_ptx_cvt_94.py::test_ptx94_pzo_normalizes_each_negative_zero_after_narrow_conversion",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.ld",
            "call:tirx.ptx.ld_vec",
            "call:tirx.ptx.ld_vec256",
            "call:tirx.ptx.prefetch",
            "call:tirx.ptx.st",
            "call:tirx.ptx.st_vec",
            "call:tirx.ptx.st_vec256",
        ),
        tests=(
            "integration/test_integer_addresses.py::test_integer_address_space_checks_ignore_inactive_lane_values",
            "integration/test_raw_memory_artifact.py::test_raw_global_nc_load_preserves_global_payload",
            "integration/test_raw_memory_artifact.py::test_pointer_derived_shared_views_raw_memory_and_cvta_preserve_aliasing",
            "integration/test_raw_memory_artifact.py::test_raw_global_load_store_modifiers_share_immediate_physical_memory",
            "integration/test_raw_memory_artifact.py::test_raw_store_predicate_selects_writing_lanes",
            "integration/test_raw_memory_artifact.py::test_raw_subword_vector_stores_preserve_each_element",
            "integration/test_raw_memory_artifact.py::test_v2_and_v8_destination_loads_move_every_element",
            "integration/test_raw_memory_artifact.py::test_ordered_v2_destination_loads_keep_their_memory_semantics",
            "integration/test_raw_memory_artifact.py::test_global_nc_v2_destination_load_moves_both_elements",
            "integration/test_raw_memory_artifact.py::test_ptx_eviction_and_prefetch_hints_preserve_loaded_values",
            "integration/test_raw_memory_artifact.py::test_raw_memory_hint_forms_preserve_loaded_and_stored_values",
            "integration/test_raw_memory_artifact.py::test_sub_word_ptx_types_extend_into_their_register_width",
            "integration/test_raw_memory_artifact.py::test_sub_word_ptx_types_keep_their_ordering_specializations",
            "microtests/test_raw_memory_forms.py::test_raw_memory_forms_match_gpu",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_mma_ss",
            "call:tirx.ptx.tcgen05_mma_ts",
            "call:tirx.ptx.tcgen05_mma_ws_ss",
            "call:tirx.ptx.tcgen05_mma_ws_ts",
        ),
        tests=(
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_bf16_shared_shared_mma_matches_independent_matrix_product",
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_tf32_shared_shared_matches_independent_matrix_product",
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_e4m3_m64_n8_uses_layout_f",
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_tf32_low32_replacement_honors_predicate_and_accumulator",
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_f16_cta2_datapaths_match_independent_matrix_products",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_mma_block_scale_ss",
            "call:tirx.ptx.tcgen05_mma_block_scale_ts",
            "call:tirx.ptx.tcgen05_mma_block_scale_block_ss",
            "call:tirx.ptx.tcgen05_mma_block_scale_block_ts",
        ),
        tests=(
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_mxf4_mqa_mma_uses_physical_smem_and_tmem_scales",
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_mixed_block_scale_cta_group2_gathers_and_scatters_both_ctas",
            "runtime/test_tcgen05_block_tmem.py::test_block_scaled_tmem_a",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.add", "tile:tirx.tile.mul", "tile:tirx.tile.sub"),
        tests=(
            "runtime/test_tile_general_semantics.py::test_integer_add_sub_mul_use_wrapping_arithmetic",
            "runtime/test_tile_codegen.py::test_contiguous_f32_uses_canonical_rn_without_ftz",
            "runtime/test_tile_general_semantics.py::test_float64_elementwise_forms_use_native_double_semantics",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.fdiv", "tile:tirx.tile.fma"),
        tests=(
            "runtime/test_tile_general_semantics.py::test_fdiv_rounding_config_matches_current_cuda_scalar_fallback",
            "runtime/test_tile_codegen.py::test_contiguous_f32_uses_canonical_rn_without_ftz",
            "runtime/test_tile_general_semantics.py::test_float64_elementwise_forms_use_native_double_semantics",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.maximum",),
        tests=(
            "runtime/test_tile_general_semantics.py::test_elementwise_maximum_matches_pairwise_values",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "tile:tirx.tile.exp",
            "tile:tirx.tile.exp2",
            "tile:tirx.tile.log2",
            "tile:tirx.tile.reciprocal",
            "tile:tirx.tile.silu",
            "tile:tirx.tile.sqrt",
        ),
        tests=(
            "runtime/test_tile_unary_codegen.py::test_unary_tile_ops_run_through_local_reg_lowering",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.fill", "tile:tirx.tile.zero"),
        tests=(
            "runtime/test_tile_unary_codegen.py::test_unary_tile_ops_run_through_local_reg_lowering",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.cast",),
        tests=(
            "runtime/test_tile_general_semantics.py::test_cast_uses_general_scalar_conversion_without_dispatch_semantics",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.copy",),
        tests=(
            "integration/test_block_scaled_gemm_artifact.py::test_fp8_scale_permute_and_sf_reuse_tmem_roundtrip",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.permute_layout",),
        tests=(
            "integration/test_permute_layout_artifact.py::test_shared_permute_layout_copies_logical_values_between_physical_layouts",
            "integration/test_permute_layout_artifact.py::test_shared_permute_layout_zero_fills_fp8_padding",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.max", "tile:tirx.tile.min", "tile:tirx.tile.sum"),
        tests=(
            "runtime/test_tile_codegen.py::test_sum_max_min_and_accum_reduce_each_lane_local_tile",
            "runtime/test_tile_reduction_variants.py::test_local_float64_reductions_match_b200_edge_bits",
            "runtime/test_tile_reduction_variants.py::test_local_integer_reductions_wrap_and_preserve_order",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.copy_async",),
        tests=(
            "integration/test_tcgen_transfer_artifact.py::test_tcgen_cp_expands_tlane_replicas",
            "integration/test_tcgen_transfer_artifact.py::test_tcgen_cp_bitcasts_uint8_scale_payload_into_float8_tmem",
            "integration/test_tcgen_transfer_artifact.py::test_tcgen_cp_cta_group2_supports_float16_payloads",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.gemm_async",),
        tests=(
            "integration/test_gemm_async_artifact.py::test_dense_gemm_async_gathers_physical_operands_and_accumulates_tmem",
            "integration/test_block_scaled_gemm_artifact.py::test_nvfp4_block_scaled_gemm_decodes_nibbles_and_e4m3_scales",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.copy_async",),
        tests=(
            "runtime/test_tile_codegen.py::test_tma_gmem_smem_roundtrip_delivers_physical_bytes_before_wait",
            "runtime/test_tile_codegen.py::test_tma_global_boundary_uses_zero_fill_and_counts_full_delivery",
            "runtime/test_tile_codegen.py::test_tma_global_boundary_uses_hardware_oob_nan_pattern",
            "runtime/test_tile_codegen.py::test_typed_tma_reduce_reuses_raw_tensor_map_reduction_abi",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.cp_async_bulk_commit_group",
            "call:tirx.ptx.cp_async_bulk_wait_group",
            "call:tirx.ptx.cp_async_commit_group",
            "call:tirx.ptx.cp_async_wait_group",
        ),
        tests=(
            "integration/test_direct_memory_artifact.py::test_raw_cp_async_issues_nonbulk_group_for_zero_fill_lanes",
            "runtime/test_tile_codegen.py::test_dsmem_copy_writes_the_named_remote_cta",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.cp_async_bulk_g2s_cluster",
            "call:tirx.ptx.cp_async_bulk_g2s_cta",
            "call:tirx.ptx.cp_async_bulk_s2g",
            "call:tirx.ptx.cp_async_bulk_s2c",
        ),
        tests=(
            "integration/test_memory_artifact.py::test_mega_one_dimensional_bulk_copy_roundtrips_bytes",
            "runtime/test_memory_ops.py::test_bulk_g2s_cta_copies_exact_physical_bytes",
        ),
    ),
    RuntimeCase(
        target_ids=tuple(
            "call:tirx.ptx." + name
            for name in (
                "cp_async_bulk_tensor_g2s_cta_override_address",
                "cp_async_bulk_tensor_g2s_cluster_override_address",
                "cp_async_bulk_tensor_s2g_override_address",
                "cp_reduce_async_bulk_tensor_override_address",
                "cp_async_bulk_tensor_prefetch_override_address",
                "cp_async_bulk_tensor_prefetch_override_address_evict_last",
                "applypriority_async_bulk_tensor_override_address",
                "cp_async_bulk_tensor_g2s_cta_override_global_dim_b8",
                "cp_async_bulk_tensor_g2s_cta_override_global_dim_b16",
                "cp_async_bulk_tensor_g2s_cluster_override_global_dim_b8",
                "cp_async_bulk_tensor_g2s_cluster_override_global_dim_b16",
                "cp_async_bulk_tensor_s2g_override_global_dim_b8",
                "cp_async_bulk_tensor_s2g_override_global_dim_b16",
                "cp_reduce_async_bulk_tensor_override_global_dim_b8",
                "cp_reduce_async_bulk_tensor_override_global_dim_b16",
                "cp_async_bulk_tensor_prefetch_override_global_dim_b8",
                "cp_async_bulk_tensor_prefetch_override_global_dim_b16",
                "cp_async_bulk_tensor_prefetch_override_global_dim_evict_last_b8",
                "cp_async_bulk_tensor_prefetch_override_global_dim_evict_last_b16",
                "applypriority_async_bulk_tensor_override_global_dim_b8",
                "applypriority_async_bulk_tensor_override_global_dim_b16",
                "cp_async_bulk_tensor_g2s_cta_override_global_dim_stride_b8",
                "cp_async_bulk_tensor_g2s_cta_override_global_dim_stride_b16",
                "cp_async_bulk_tensor_g2s_cluster_override_global_dim_stride_b8",
                "cp_async_bulk_tensor_g2s_cluster_override_global_dim_stride_b16",
                "cp_async_bulk_tensor_s2g_override_global_dim_stride_b8",
                "cp_async_bulk_tensor_s2g_override_global_dim_stride_b16",
                "cp_reduce_async_bulk_tensor_override_global_dim_stride_b8",
                "cp_reduce_async_bulk_tensor_override_global_dim_stride_b16",
                "cp_async_bulk_tensor_prefetch_override_global_dim_stride_b8",
                "cp_async_bulk_tensor_prefetch_override_global_dim_stride_b16",
                "cp_async_bulk_tensor_prefetch_override_global_dim_stride_evict_last_b8",
                "cp_async_bulk_tensor_prefetch_override_global_dim_stride_evict_last_b16",
                "applypriority_async_bulk_tensor_override_global_dim_stride_b8",
                "applypriority_async_bulk_tensor_override_global_dim_stride_b16",
            )
        ),
        tests=("runtime/test_tma_overrides.py::test_tma_override_data_and_descriptor_isolation",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.cp_async_bulk_g2s_cluster_multicast16",
            "call:tirx.ptx.cp_async_bulk_g2s_cluster_multicast32",
        ),
        tests=(
            "runtime/test_multicast16.py::test_bulk_multicast16_preserves_lane_resolved_targets",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.tcgen05_commit_multicast_width",),
        tests=("runtime/test_multicast16.py::test_tcgen_multicast16_preserves_commit_targets",),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.mbarrier_pending_count",),
        tests=(
            "runtime/test_mbarrier_pending_count.py::test_pending_count_snapshot",
            "runtime/test_sync_instruction_predicates.py::test_pending_count_instruction_predicates",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.cp_reduce_async_bulk_s2g",),
        tests=(
            "runtime/test_bulk_reduce_s2g_f32.py::test_bulk_reduce_is_atomic_captures_source_and_publishes_only_at_full_wait",
            "runtime/test_bulk_reduce_s2g_f32.py::test_bulk_reduce_is_atomic_across_ctas_without_lost_updates",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.atom_f32_noftz",
            "call:tirx.ptx.atom_f32_noftz_bitbucket",
            "call:tirx.ptx.red_f32_noftz",
            "call:tirx.ptx.atom_vec_f32_noftz",
            "call:tirx.ptx.atom_vec_f32_noftz_bitbucket",
            "call:tirx.ptx.red_vec_f32_noftz",
        ),
        tests=("runtime/test_atomic_f32_noftz.py::test_atomic_f32_noftz",),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.cp_reduce_async_bulk_s2g_f32_noftz",),
        tests=("runtime/test_atomic_f32_noftz.py::test_bulk_f32_noftz",),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.cp_async_mbarrier_arrive",),
        tests=(
            "runtime/test_sync_runtime_domain_oracle.py::test_ordering_and_cp_async_mbarrier_modifier_forms_preserve_values",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.copy_async",),
        tests=("runtime/test_tile_codegen.py::test_ldgsts_copy_keeps_cooperative_warp_lowering",),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.copy_async",),
        tests=("runtime/test_tile_codegen.py::test_dsmem_copy_writes_the_named_remote_cta",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.cp_async_ca",
            "call:tirx.ptx.cp_async_ca_ignore_src",
            "call:tirx.ptx.cp_async_ca_src_size",
            "call:tirx.ptx.cp_async_cg",
            "call:tirx.ptx.cp_async_cg_ignore_src",
            "call:tirx.ptx.cp_async_cg_src_size",
        ),
        tests=(
            "integration/test_direct_memory_artifact.py::test_raw_cp_async_issues_nonbulk_group_for_zero_fill_lanes",
            "integration/test_direct_memory_artifact.py::test_pass_emitted_cp_async_raw_restores_element_offsets",
            "runtime/test_memory_ops.py::test_cp_async_ignore_src_skips_oob_reads_and_zero_fills",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.st_async_vec",),
        tests=(
            "runtime/test_non_tensor_bulk_forms.py::test_raw_st_async_preserves_mapped_remote_cta_ownership",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.__shfl_down_sync",
            "call:tirx.cuda.__shfl_sync",
            "call:tirx.cuda.__shfl_up_sync",
            "call:tirx.cuda.__shfl_xor_sync",
            "call:tirx.cuda.ballot_sync",
            "call:tirx.cuda.any_sync",
        ),
        tests=(
            "integration/test_warp_ops_artifact.py::test_warp_intrinsics_use_typed_engine_calls",
            "runtime/test_cuda_packed_vector_forms.py::test_cuda_shuffles_preserve_bfloat16x2_payload_bits",
            "runtime/test_scalar_control.py::test_scalar_and_warp_intrinsics_execute_with_native_semantics",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.reduce_add_sync_u32",
            "call:tirx.cuda.reduce_min_sync_u32",
            "call:tirx.cuda.warp_reduce",
        ),
        tests=(
            "integration/test_warp_ops_artifact.py::test_warp_intrinsics_use_typed_engine_calls",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.cta_reduce",
            "call:tirx.cuda.syncthreads_and",
            "call:tirx.cuda.syncthreads_or",
        ),
        tests=(
            "integration/test_artifact_build.py::test_cta_reductions_preserve_each_warp_partial_in_scratch",
            "runtime/test_scalar_control.py::test_cta_votes_grid_sync_and_ordering_markers",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.mbarrier_arrive_count_state",
            "call:tirx.ptx.mbarrier_try_wait",
        ),
        tests=(
            "runtime/test_scalar_control.py::test_mbarrier_arrival_state_token_selects_the_exact_completed_generation",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.mbarrier_test_wait_parity",
            "call:tirx.ptx.mbarrier_try_wait_parity",
            "call:tirx.ptx.mbarrier_try_wait_parity_no_hint",
        ),
        tests=("runtime/test_scalar_control.py::test_mbarrier_one_shot_queries_observe_parity",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.cluster_sync",
            "call:tirx.cuda.cta_sync",
            "call:tirx.cuda.grid_sync",
            "call:tirx.cuda.warp_sync",
            "call:tirx.cuda.warpgroup_sync",
            "call:tirx.ptx.bar_arrive",
            "call:tirx.ptx.bar_sync",
            "call:tirx.ptx.bar_sync_count",
            "call:tirx.ptx.bar_warp_sync",
            "call:tirx.ptx.barrier_arrive",
            "call:tirx.ptx.barrier_sync",
            "call:tirx.ptx.barrier_sync_count",
        ),
        tests=(
            "integration/test_artifact_build.py::test_cluster_rendezvous_accepts_complete_cluster_selections",
            "runtime/test_scalar_control.py::test_cta_votes_grid_sync_and_ordering_markers",
            "runtime/test_scalar_control.py::test_named_barrier_arrive_contributes_without_blocking",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.barrier_cluster_arrive",),
        tests=(
            "integration/test_memory_artifact.py::test_cluster_barrier_accepts_default_release_and_unaligned_forms",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.mbarrier_expect_tx",),
        tests=(
            "runtime/test_mbarrier_lane_semantics.py::test_standalone_mbarrier_expect_tx_arms_without_consuming_an_arrival",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.mbarrier_arrive",
            "call:tirx.ptx.mbarrier_arrive_nocount",
            "call:tirx.ptx.mbarrier_arrive_expect_tx",
            "call:tirx.ptx.mbarrier_arrive_no_complete",
            "call:tirx.ptx.mbarrier_complete_tx",
            "call:tirx.ptx.mbarrier_init",
        ),
        tests=(
            "integration/test_artifact_build.py::test_physical_mbarrier_reuses_phase_and_completes_numeric_transactions_directly",
            "runtime/test_mbarrier_lane_semantics.py::test_current_mbarrier_arrival_and_completion_forms_advance_protocol",
            "runtime/test_mbarrier_lane_semantics.py::test_mbarrier_init_honors_elected_lane_predicate",
            "runtime/test_tile_codegen.py::test_dsmem_copy_writes_the_named_remote_cta",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.thread_fence",
            "call:tirx.ptx.fence",
            "call:tirx.ptx.fence_mbarrier_init",
            "call:tirx.ptx.fence_proxy",
            "call:tirx.ptx.griddepcontrol",
            "call:tirx.ptx.setmaxnreg",
        ),
        tests=(
            "runtime/test_ordering_calls.py::test_ordering_only_calls_preserve_native_source_order",
            "runtime/test_ordering_calls.py::test_setmaxnreg_is_an_ordering_call_not_a_tcgen_lifecycle_call",
            "runtime/test_scalar_control.py::test_cta_votes_grid_sync_and_ordering_markers",
            "integration/test_memory_artifact.py::test_non_tensor_bulk_copy_executes_independently_for_every_active_lane",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.cuda.nano_sleep", "call:tirx.cuda.printf"),
        tests=("runtime/test_scalar_control.py::test_cta_votes_grid_sync_and_ordering_markers",),
    ),
    RuntimeCase(
        target_ids=("call:tirx.cuda.trap_when_assert_failed",),
        tests=(
            "runtime/test_scalar_control.py::test_integer_trap_predicate_uses_cpp_truth_conversion",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.__activemask",
            "call:tirx.cuda.clock64",
            "call:tirx.cuda.thread_rank",
            "call:tirx.timer_end_cuda",
            "call:tirx.timer_finalize_cuda",
            "call:tirx.timer_init_cuda",
            "call:tirx.timer_start_cuda",
            "call:tirx.tvm_warp_activemask",
        ),
        tests=(
            "runtime/test_scalar_control.py::test_scalar_and_warp_intrinsics_execute_with_native_semantics",
            "runtime/test_scalar_control.py::test_timer_finalize_is_a_numerical_noop",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.gemm",),
        tests=(
            "integration/test_warp_gemm_artifact.py::test_warp_gemm_gathers_and_scatters_register_fragments_by_layout",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.ldmatrix",),
        tests=(
            "integration/test_raw_memory_artifact.py::test_raw_ldmatrix_x4_b16_uses_ptx_address_and_fragment_lane_mapping",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.ldmatrix_m16n16_b8", "call:tirx.ptx.ldmatrix_b8fmt"),
        tests=("runtime/test_ldmatrix_b8.py::test_ldmatrix_b8_layouts",),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx_legacy.ldmatrix",),
        tests=(
            "runtime/test_memory_ops.py::test_legacy_ldmatrix_transpose_preserves_b16_fragment_abi",
            "runtime/test_memory_ops.py::test_legacy_ldmatrix_8bit_transpose_matches_tirx_manual_gather",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.stmatrix", "call:tirx.ptx.stmatrix_m16n8_b8"),
        tests=(
            "microtests/test_matrix_memory.py::test_matrix_memory_matches_gpu[stmatrix_b16_x1]",
            "microtests/test_matrix_memory.py::test_matrix_memory_matches_gpu[stmatrix_b8_x1_and_b16_x4_trans]",
            "microtests/test_matrix_memory.py::test_matrix_memory_matches_gpu[stmatrix_b8_and_b16_x2]",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.stmatrix",),
        tests=(
            "microtests/test_matrix_memory.py::test_matrix_memory_matches_gpu[stmatrix_b8_x4_trans]",
            "microtests/test_matrix_memory.py::test_matrix_memory_matches_gpu[stmatrix_b8_x1_and_b16_x4_trans]",
            "microtests/test_matrix_memory.py::test_matrix_memory_matches_gpu[stmatrix_b8_and_b16_x2]",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.mma",
            "call:tirx.ptx.mma_f16acc",
            "call:tirx.ptx.mma_f16c_f32d",
            "call:tirx.ptx.mma_f64",
        ),
        tests=(
            "runtime/test_dense_mma_forms.py::test_m16n8k8_f16_accumulator_uses_packed_output_registers",
            "runtime/test_dense_mma_forms.py::test_m16n8k4_tf32_mma_matches_tf32_reference",
            "runtime/test_dense_mma_forms.py::test_m8n8k4_f64_mma_matches_fused_reference",
            "runtime/test_dense_mma_forms.py::test_m16n8k16_f64_mma_matches_fused_reference",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.mma", "call:tirx.ptx.mma_int"),
        tests=(
            "runtime/test_dense_mma_forms.py::test_m16n8k32_mixed_int8_mma_matches_integer_reference",
            "runtime/test_dense_mma_forms.py::test_m16n8k32_int4_uses_packed_b32_fragment_abi",
            "runtime/test_dense_mma_forms.py::test_m16n8k128_b1_xor_popc_matches_logical_reference",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.mma",),
        tests=(
            "runtime/test_dense_mma_forms.py::test_m16n8k32_mixed_fp8_uses_packed_fragment_abi",
            "runtime/test_dense_mma_forms.py::test_m16n8k16_mixed_fp8_supports_f16_accumulator",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx_legacy.mma",),
        tests=(
            "runtime/test_dense_mma_forms.py::test_legacy_m16n8k32_int8_reuses_dense_form_and_engine",
            "runtime/test_matrix_instruction_codegen.py::test_ptx_mma_legacy_executes_actual_pointer_offset_abi",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.mma_fill",
            "call:tirx.mma_fill_legacy",
            "call:tirx.mma_store",
            "call:tirx.mma_store_legacy",
        ),
        tests=(
            "runtime/test_matrix_instruction_codegen.py::test_mma_fragment_fill_and_store_observe_lane_register_layout",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.mma_sp",
            "call:tirx.ptx.mma_sp_all",
            "call:tirx.ptx.mma_sp_f16acc",
            "call:tirx.ptx.mma_sp_f16acc_pair",
            "call:tirx.ptx.mma_sp_int_all",
            "call:tirx.ptx.mma_sp_int_pair",
            "call:tirx.ptx.mma_sp_pair",
        ),
        tests=(
            "runtime/test_sparse_mma_forms.py::test_sparse_f16_k32_uses_thread_pair_metadata",
            "runtime/test_sparse_mma_forms.py::test_sparse_tf32_k8_uses_one_of_two_metadata",
            "runtime/test_sparse_mma_forms.py::test_sparse_int8_k64_uses_all_thread_metadata",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.cuda.atomic_add",),
        tests=(
            "runtime/test_memory_ops.py::test_cuda_float_atomic_add_and_default_st_bulk_forms",
            "runtime/test_memory_ops.py::test_cuda_16bit_float_atomic_add_uses_16bit_storage",
            "runtime/test_memory_ops.py::test_cuda_float32x2_atomic_add_updates_components_and_returns_old_pairs",
            "runtime/test_memory_ops.py::test_cuda_float32x4_atomic_add_is_componentwise",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.cuda.atomic_cas",),
        tests=(
            "integration/test_memory_artifact.py::test_global_i32_atomic_cas_returns_old_and_only_writes_on_compare_success",
            "runtime/test_memory_ops.py::test_cuda_128bit_atomic_cas_compares_float_vectors_by_bits",
            "runtime/test_memory_ops.py::test_cuda_128bit_atomic_cas_uses_generic_total_width_vector_abi",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.atom",
            "call:tirx.ptx.atom_cas",
            "call:tirx.ptx.atom_vec_f32",
            "call:tirx.ptx.red",
            "call:tirx.ptx.red_half",
        ),
        tests=(
            "runtime/test_ptx_atomic_cas.py::test_atom_cas_returns_the_prior_value_and_swaps",
            "integration/test_memory_artifact.py::test_mega_atomic_and_reduction_signatures_execute_exactly",
            "runtime/test_memory_ops.py::test_ptx_atomics_apply_instruction_type_after_relaxed_operand_conformance",
            "runtime/test_memory_ops.py::test_ptx_vector_f32_atomic_add_uses_scalar_storage_and_predicate",
            "runtime/test_memory_ops.py::test_ptx_red_half_bfloat16x2_reduces_both_components",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.st_bulk",),
        tests=(
            "runtime/test_non_tensor_bulk_forms.py::test_st_bulk_size_is_evaluated_per_issuing_lane",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.tvm_access_ptr",),
        tests=(
            "integration/test_direct_memory_artifact.py::test_decl_buffer_views_preserve_permitted_accesses",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.address_of", "call:tirx.cuda.smem_addr_from_uint64"),
        tests=(
            "integration/test_artifact_build.py::test_address_of_lowers_to_integer_bits_before_program_use",
            "runtime/test_scalar_control.py::test_scalar_and_warp_intrinsics_execute_with_native_semantics",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.mapa", "call:tirx.ptx.mapa_u32"),
        tests=(
            "integration/test_artifact_build.py::test_mapa_remote_shared_writes_use_the_target_ctas_owner",
            "runtime/test_scalar_control.py::test_canonical_mapa_integer_address_resolves_shared_memory",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.cvta",),
        tests=(
            "runtime/test_scalar_control.py::test_public_cvta_shared_cluster_u64_zero_extends_shared_addresses",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.addr",),
        tests=("runtime/test_ptx_addr_runtime.py::test_ptx_addr_applies_a_signed_byte_offset",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.cvta_generic_to_shared",
            "call:tirx.ptr_byte_offset",
            "call:tirx.s_tir.ldg32",
            "call:tirx.type_annotation",
        ),
        tests=(
            "integration/test_raw_memory_artifact.py::test_pointer_derived_shared_views_raw_memory_and_cvta_preserve_aliasing",
            "integration/test_raw_memory_artifact.py::test_raw_global_load_store_modifiers_share_immediate_physical_memory",
            "integration/test_raw_memory_artifact.py::test_ordered_v2_destination_loads_keep_their_memory_semantics",
            "runtime/test_memory_ops.py::test_legacy_acquire_and_guarded_ldg32_write_local_lvalues",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.break_loop", "call:tirx.continue_loop"),
        tests=(
            "integration/test_artifact_build.py::test_divergent_break_and_continue_use_loop_masks",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.ffs_u32",
            "call:tirx.popcount",
        ),
        tests=(
            "integration/test_artifact_build.py::test_typed_raw_scalar_calls_execute_with_warp_semantics",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.exp", "call:tirx.fma", "call:tirx.log", "call:tirx.rsqrt"),
        tests=(
            "integration/test_artifact_build.py::test_typed_raw_scalar_calls_execute_with_warp_semantics",
        ),
    ),
    RuntimeCase(
        target_ids=("call:prim.log2",),
        tests=(
            "runtime/test_scalar_control.py::test_current_scalar_device_intrinsics_have_stable_numeric_representatives",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.lg2",),
        tests=(
            "../analysis_tools/shared/test_known_cuda_func_artifact.py::test_known_gdn_lg2_approx_ftz_flushes_subnormal_input",
            "../analysis_tools/synccheck/runtime/test_device_additional_payload_ops.py::test_payload_runtime[direct_lg2_payload]",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.rsqrt", "call:tirx.ptx.tanh"),
        tests=(
            "runtime/test_approximate_f32_contract.py::test_rsqrt_approx_ftz_representative_executes",
            "runtime/test_approximate_f32_contract.py::test_tanh_approx_representative_executes",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.tanh_half",),
        tests=(
            "runtime/test_approximate_f32_contract.py::test_f16x2_tanh_approx_representative_executes",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.fabs", "call:tirx.log1p", "call:tirx.sigmoid"),
        tests=("runtime/test_gate_intrinsics.py::test_gate_intrinsics_match_float32_semantics",),
    ),
    RuntimeCase(
        target_ids=("call:prim.if_then_else",),
        tests=(
            "runtime/test_dynamic_pure_call_runtime_domains.py::test_complete_if_then_else_domain_executes_both_branches",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.float22half2",
            "call:tirx.cuda.float8tohalf8",
            "call:tirx.cuda.half8tofloat8",
            "call:tirx.cuda.runtime_instr_desc",
        ),
        tests=(
            "runtime/test_scalar_control.py::test_pointer_conversions_and_runtime_descriptor_patch",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.add",
            "call:tirx.ptx.fma",
            "call:tirx.ptx.mul",
            "call:tirx.ptx.sub",
        ),
        tests=(
            "runtime/test_scalar_control.py::test_ptx_dps_rounding_ftz_and_saturation_forms",
            "integration/test_artifact_build.py::test_dps_float_arithmetic_writes_through_lane_private_physical_pointers",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.div_f",
        ),
        tests=(
            "runtime/test_scalar_f64_rounding.py::test_scalar_f64_rounding",
            "runtime/test_scalar_f64_rounding.py::test_scalar_f64_rounding_gpu",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.rcp",
        ),
        tests=(
            "runtime/test_ftz_rounding.py::test_ftz_rounding_boundary",
            "runtime/test_ftz_rounding.py::test_ftz_rounding_boundary_gpu",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.add_half",
            "call:tirx.ptx.sub_half",
        ),
        tests=(
            "runtime/test_register_extensions.py::test_register_extensions",
            "runtime/test_register_extensions.py::test_register_extensions_gpu",
            "runtime/test_packed_f16x2_arithmetic.py::test_half_subtract_modifiers",
            "runtime/test_packed_f16x2_arithmetic.py::test_scalar_f16_add_rounds_once_to_binary16",
            "runtime/test_packed_f16x2_arithmetic.py::test_packed_f16x2_subtracts_both_halves_with_one_rounding_step",
            "runtime/test_packed_f16x2_arithmetic.py::test_packed_bf16x2_subtracts_both_halves_with_one_rounding_step",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.bfloat1622float2",
            "call:tirx.cuda.bfloat162float",
            "call:tirx.cuda.fadd2_rn",
            "call:tirx.cuda.float22bfloat162_rn",
            "call:tirx.cuda.float22bfloat162_rn_from_float2",
            "call:tirx.cuda.float2_x",
            "call:tirx.cuda.float2_y",
            "call:tirx.cuda.float_as_uint",
            "call:tirx.cuda.fmul2_rn",
            "call:tirx.cuda.fp8x4_e4m3_from_float4",
            "call:tirx.cuda.half2float",
            "call:tirx.cuda.hmax2",
            "call:tirx.cuda.hmin2",
            "call:tirx.cuda.make_float2",
            "call:tirx.cuda.uint_as_float",
        ),
        tests=(
            "runtime/test_scalar_helpers.py::test_mega_scalar_helpers_match_packed_numeric_semantics",
            "runtime/test_scalar_control.py::test_cuda_packed_ops_use_gpu_canonical_nan_encodings",
            "runtime/test_scalar_control.py::test_scalar_and_warp_intrinsics_execute_with_native_semantics",
            "integration/test_artifact_build.py::test_typed_raw_scalar_calls_execute_with_warp_semantics",
            "integration/test_warp_ops_artifact.py::test_warp_intrinsics_use_typed_engine_calls",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.ex2",
        ),
        tests=(
            "integration/test_artifact_build.py::test_warp_local_raw_calls_execute_inside_one_warp_unit",
            "integration/test_artifact_build.py::test_typed_raw_scalar_calls_execute_with_warp_semantics",
            "runtime/test_ptx_register_bits.py::test_latest_canonical_scalar_forms_match_independent_numpy_oracle",
            "runtime/test_scalar_helpers.py::test_mega_scalar_helpers_match_packed_numeric_semantics",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.ex2_half",),
        tests=(
            "runtime/test_approximate_f32_contract.py::test_bf16x2_exp2_executes_both_lanes_and_flushes_bf16_subnormals",
            "runtime/test_approximate_f32_contract.py::test_f16x2_exp2_executes_both_lanes_and_preserves_subnormal_results",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.min",
            "call:tirx.ptx.max",
            "call:tirx.ptx.min3",
            "call:tirx.ptx.max3",
        ),
        tests=(
            "runtime/test_register_extensions.py::test_register_extensions",
            "runtime/test_register_extensions.py::test_register_extensions_gpu",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.elect_sync",
            "call:tirx.tvm_warp_shuffle",
            "call:tirx.tvm_warp_shuffle_up",
            "call:tirx.tvm_warp_shuffle_down",
            "call:tirx.tvm_warp_shuffle_xor",
        ),
        tests=(
            "integration/test_artifact_build.py::test_typed_raw_scalar_calls_execute_with_warp_semantics",
            "integration/test_artifact_build.py::test_warp_local_raw_calls_execute_inside_one_warp_unit",
            "integration/test_warp_ops_artifact.py::test_warp_intrinsics_use_typed_engine_calls",
            "runtime/test_dynamic_pure_call_runtime_domains.py::test_complete_tvm_shuffle_payload_domain_executes",
        ),
    ),
    RuntimeCase(
        target_ids=("tile:tirx.tile.copy_async",),
        tests=(
            "integration/test_tcgen_transfer_artifact.py::test_tcgen_tmem_to_wg_local_uses_layout_owners",
            "integration/test_tcgen_transfer_artifact.py::test_tcgen_wg_local_to_tmem_uses_one_physical_writer",
            "integration/test_tcgen_transfer_artifact.py::test_tcgen_16xb_roundtrip_preserves_16bit_register_halves",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.cuda.get_tmem_addr",),
        tests=(
            "integration/test_raw_memory_artifact.py::test_get_tmem_addr_packs_wrapped_row_and_column_offsets_per_lane",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.tcgen05_encode_instr_descriptor",
            "call:tirx.cuda.tcgen05_encode_instr_descriptor_block_scaled",
            "call:tirx.cuda.tcgen05_encode_matrix_descriptor",
        ),
        tests=(
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_descriptor_encoders_write_exact_bits",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_ld",
            "call:tirx.ptx.tcgen05_ld_split",
            "call:tirx.ptx.tcgen05_st",
            "call:tirx.ptx.tcgen05_st_split",
        ),
        tests=(
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_32x32b_ld_st_roundtrip",
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_16x256b_ld_observes_exact_lane_register_mapping",
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_missing_ld_shapes_observe_exact_lane_register_mappings",
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_ld_pack_and_st_unpack_use_adjacent_tmem_columns",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.tcgen05_ld_red", "call:tirx.ptx.tcgen05_ld_red_split"),
        tests=(
            "runtime/test_tcgen05_ld_red.py::test_tcgen_load_reduction_matches_column_oracle",
            "runtime/test_tcgen05_ld_red.py::test_tcgen_load_reduction_preserves_the_store_wait_contract",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_ld_spcompress",
            "call:tirx.ptx.tcgen05_ld_red_spcompress",
        ),
        tests=(
            "runtime/test_tcgen05_ld_spcompress.py::test_tcgen_load_compression",
            "runtime/test_tcgen05_ld_spcompress.py::test_tcgen_compression_preserves_store_wait",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.cp_reduce_async_bulk_s2c",),
        tests=("runtime/test_red_async.py::test_shared_async_reduction_completion",),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.discard",),
        tests=(
            "runtime/test_discard.py::test_discard_range_and_predication",
            "runtime/test_discard.py::test_discard_indeterminate_read_and_alignment",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.ptx.tcgen05_cp",),
        tests=(
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_cp_warpx4_replicates_source_into_all_warp_lanes",
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_cp_covers_4x256b_and_both_warpx2_pairings",
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_cp_decompression_expands_packed_codes",
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_cp_cta_group2_writes_both_ctas_with_warpx2_routing",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_alloc",
            "call:tirx.ptx.tcgen05_alloc_exclusive",
            "call:tirx.ptx.tcgen05_dealloc",
            "call:tirx.ptx.tcgen05_dealloc_exclusive",
            "call:tirx.ptx.tcgen05_relinquish_alloc_permit",
        ),
        tests=(
            "runtime/test_tcgen_codegen.py::test_tcgen_two_cta_lifecycle_rendezvous",
            "runtime/test_launch_resource_facts.py::test_exclusive_tmem_uses_cta_local_lifecycle_without_placement",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_commit_sync_restrict",
            "call:tirx.ptx.tcgen05_commit_sync_restrict_multicast",
        ),
        tests=(
            "runtime/test_tcgen_commit_predicates.py::test_tcgen_commit_predicates_gate_all_operands",
            "microtests/test_tcgen_commit_predicates.py::test_tcgen_commit_predicates_gpu",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.tcgen05_commit",
            "call:tirx.ptx.tcgen05_commit_multicast",
            "call:tirx.ptx.tcgen05_fence",
            "call:tirx.ptx.tcgen05_wait",
        ),
        tests=(
            "runtime/test_tcgen_codegen.py::test_tcgen_commit_arrives_on_physical_mbarrier",
            "runtime/test_tcgen_codegen.py::test_tcgen_commit_runtime_mask_multicasts_same_barrier_offset",
            "runtime/test_tcgen_codegen.py::test_tcgen_fence_forms_are_numerical_noops",
            "runtime/test_raw_tcgen_codegen.py::test_raw_tcgen_32x32b_ld_st_roundtrip",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.cuda.sm100_2sm_leader_smem_addr",),
        tests=(
            "runtime/test_scalar_control.py::test_scalar_and_warp_intrinsics_execute_with_native_semantics",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.fence_proxy_tensormap_acquire",
            "call:tirx.ptx.fence_proxy_tensormap_release",
            "call:tirx.ptx.tensormap_replace_address",
            "call:tirx.ptx.tensormap_replace_dim",
            "call:tirx.ptx.tensormap_replace_stride",
        ),
        tests=(
            "runtime/test_raw_tensor_map_descriptors.py::test_typed_payload_copy_replace_release_and_acquire_drive_raw_tma",
            "../analysis_tools/synccheck/runtime/test_device_additional_payload_ops.py::test_payload_runtime[direct_tensor_map_payload_ops]",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.cuda.wait_until",
        ),
        tests=(
            "runtime/test_wait_until.py::test_rendezvous_matches_raw_spelling",
            "runtime/test_wait_until.py::test_a_backoff_is_the_cuda_loops_business_and_not_the_engines",
            "runtime/test_wait_until.py::test_declared_rendezvous_is_clean",
            "runtime/test_wait_until.py::test_packed_wait_matches_raw_spelling",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.address_of",),
        tests=(
            "runtime/test_raw_tma_codegen.py::test_raw_tma_s2g_returns_the_tensor_map_output",
            "runtime/test_raw_tma_codegen.py::test_raw_tma_tensor_map_selector_branches_at_runtime",
        ),
    ),
    RuntimeCase(
        target_ids=("call:tirx.nvshmem.my_pe", "call:tirx.nvshmem.n_pes"),
        tests=("runtime/test_multimem.py::test_nvshmem_rank_queries_report_the_launch",),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.multimem_ld_reduce",
            "call:tirx.ptx.multimem_ld_reduce_f",
            "call:tirx.ptx.multimem_ld_reduce_f_vec",
        ),
        tests=(
            "runtime/test_multimem.py::test_ld_reduce_returns_the_same_sum_on_every_rank",
            "runtime/test_multimem.py::test_float_ld_reduce_models_the_nvls_accumulator",
            "runtime/test_multimem.py::test_one_shot_all_reduce_gives_every_rank_the_sum",
            "runtime/test_multimem_kernels.py::test_cutlass_two_shot_all_reduce_sums_every_rank",
            "microtests/test_multimem.py::test_multimem_matches_gpu",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.multimem_red",
            "call:tirx.ptx.multimem_red_f",
            "call:tirx.ptx.multimem_red_f_vec",
        ),
        tests=(
            "runtime/test_multimem.py::test_red_reduces_into_each_replica",
            "runtime/test_multimem.py::test_float_red_adds_exactly_and_f32_flushes_subnormals",
            "microtests/test_multimem.py::test_multimem_matches_gpu",
        ),
    ),
    RuntimeCase(
        target_ids=(
            "call:tirx.ptx.multimem_st",
            "call:tirx.ptx.multimem_st_f",
            "call:tirx.ptx.multimem_st_f_vec",
        ),
        tests=(
            "runtime/test_multimem.py::test_st_writes_every_replica",
            "runtime/test_multimem_kernels.py::test_gemm_all_reduce_two_shot_sums_every_rank",
            "microtests/test_multimem.py::test_multimem_matches_gpu",
        ),
    ),
)


__all__ = ["RUNTIME_CASES", "RuntimeCase"]
